export const SET_ITEM = 'SET_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CHOOSED_ITEM = 'CHOOSED_ITEM';
export const REMOVE_CHOOSED_ITEM = 'REMOVE_CHOOSED_ITEM'
export const SET_FILTERED_DATA = 'SET_FILTERED_DATA';
export const SET_DATA = 'SET_DATA';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_CURRENT_FILTERED_PAGE = 'SET_CURRENT_FILTERED_PAGE';